name: Package using PyInstaller
description: Bundles a Python application and all its dependencies into a single package.

inputs:
  spec-path:
    description: Path of Spec file
    required: false
    default: "pydglab-ws-connector.spec"

  dist-path:
    description: Path of Spec file
    required: false
    default: "dist"

runs:
  using: "composite"
  steps:
    - name: Create Executable
      run: poetry run pyinstaller ${{ inputs.spec-path }} --distpath
      shell: bash

    - name: Copy Extra Files
      run: cp README.md pydglab-ws-connector/.env LICENSE ${{ inputs.dist-path }}
      shell: bash