name: GitHub Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  python-package:
    uses: ./.github/workflows/python-package.yml

  # msbuild:
  #   uses: ./.github/workflows/msbuild.yml

  release:
    runs-on: ubuntu-latest
    needs:
      - python-package
      # - msbuild

    steps:
      - uses: actions/checkout@v4

      - name: Download Python executable
        uses: actions/download-artifact@v4
        with:
          name: pydglab-ws-connector-windows-latest
          path: artifacts/python-package

      # - name: Download MSBuild artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: dglabiemod-Release
      #     path: artifacts/msbuild/Release

      # - name: Download MSBuild Debug artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: dglabiemod-Debug
      #     path: artifacts/msbuild/Debug

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          prerelease: ${{ contains(github.ref, 'beta') }}
          files: |
            artifacts/python-package/PyDGLab-WS-Connector.exe
          # files: |
          #   artifacts/python-package/PyDGLab-WS-Connector.exe
          #   artifacts/msbuild/Release/*
          #   artifacts/msbuild/Debug/*
